---
title: "USAMS112321 Carb Sputter"
author: "Brett Longworth"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(amstools)
```

Functions for adding consensus value and blank correction.

```{r}
add_consenus <- function(df) {
  # get rec_num
  db <- conNOSAMS()
  query <- glue::glue_sql("SELECT tp_num, rec_num
             FROM target
             WHERE tp_num IN ({tpnums*})",
             tpnums = df[['tp_num']],
             .con = db
  )
  
  recs <- odbc::dbSendQuery(db, query)
  recnums <- odbc::dbFetch(recs)
  odbc::dbClearResult(recs)
  df <- left_join(df, recnums)
  # get cons table
  std <- amstools::getStdTable()
  # join on rec_num
  df %>%  
    left_join(select(std, rec_num, fm_consensus), by = "rec_num") %>% 
    mutate(fm_consensus = case_when(rec_num == 101730 ~ 1.0398,
                                    rec_num == 72446 ~ 0.0013,
                                    TRUE ~ fm_consensus))
}

blank_cor_carb <- function(data, blanks = NULL, fmstd = 1.0398) {
  if (!is.null(blanks)) {
    data <- data %>% 
      mutate(sample_type = case_when(wheel_pos %in% blanks ~ "B",
                                     sample_type == "B" ~ "U",
                                     TRUE ~ sample_type ))
  }
  
  blanks <- data %>% 
    filter(sample_type == "B")
  
  data['sig_norm_ratio'] <- pmax(data['int_err'], data['ext_err'])
  
  meanblank <- mean(blanks$norm_ratio)
  
  # get blank error using SNICSer error floor
  blankerr <- amstools::blankErr(blanks$norm_ratio, blanks$sig_norm_ratio) # uses SNICSer error floor method
  # apply blank correction and propagate error
  data %>% 
    mutate(fm_corr = amstools::doLBC(norm_ratio, meanblank, fmstd),
           sig_fm_corr = amstools::doLBCerr(norm_ratio, meanblank, fmstd, sig_norm_ratio, blankerr)
    )
}
```

Load data, blank correct, add consensus values and comparison to consensus

```{r}
# consensus value for druffel coral
dcmean <- 0.9413

df <- getWheel("USAMS112321") %>% 
  blank_cor_carb(blanks = c(4,5)) %>% 
  add_consenus() %>% 
  mutate(fm_consensus = ifelse(rec_num == 21308, dcmean, fm_consensus),
         fm_diff = fm_corr - fm_consensus,
         sigma = amstools::sigma(fm_corr, fm_consensus, sig_fm_corr))
```
```{r}
df %>% 
  filter(wheel_pos %in% c(2,3,4,5,7,8,9,10)) %>% 
select(sample_name, norm_ratio, sig_norm_ratio, fm_corr, sig_fm_corr, fm_diff, sigma) %>%  
knitr::kable()
```

```{r}
df %>% 
  filter(wheel_pos %in% c(2,3,4,5,7,8,9,10)) %>% 
ggplot(aes(fm_corr, fm_diff)) +
  geom_point()
```


